local M = {}

M.SCRIPT_NAME = "AI Part Generator"

M.BRIDGE_BASE_URL = "http://127.0.0.1:8000"
M.BRIDGE_GENERATE_PATH = "/generate"
M.BRIDGE_PLAN_PATH = "/plan"
M.BRIDGE_ENHANCE_PATH = "/enhance"
M.BRIDGE_ARRANGE_PLAN_PATH = "/arrange_plan"
M.BRIDGE_HEALTH_PATH = "/health"
M.BRIDGE_GENERATE_URL = M.BRIDGE_BASE_URL .. M.BRIDGE_GENERATE_PATH
M.BRIDGE_PLAN_URL = M.BRIDGE_BASE_URL .. M.BRIDGE_PLAN_PATH
M.BRIDGE_ENHANCE_URL = M.BRIDGE_BASE_URL .. M.BRIDGE_ENHANCE_PATH
M.BRIDGE_ARRANGE_PLAN_URL = M.BRIDGE_BASE_URL .. M.BRIDGE_ARRANGE_PLAN_PATH
M.BRIDGE_HEALTH_URL = M.BRIDGE_BASE_URL .. M.BRIDGE_HEALTH_PATH

M.DEFAULT_BRIDGE_URL = M.BRIDGE_GENERATE_URL
M.DEFAULT_MODEL_PROVIDER = "lmstudio"
M.DEFAULT_MODEL_NAME = "gemma-3-4b-it-uncensored"
M.DEFAULT_MODEL_TEMPERATURE = 0.8
M.DEFAULT_MODEL_BASE_URL = "http://127.0.0.1:1234/v1"

M.HTTP_TIMEOUT_SEC = 300
M.PROCESS_TIMEOUT_BUFFER_SEC = 5
M.MS_PER_SEC = 1000
M.PROCESS_TIMEOUT_MS = (M.HTTP_TIMEOUT_SEC + M.PROCESS_TIMEOUT_BUFFER_SEC) * M.MS_PER_SEC

M.BRIDGE_PING_TIMEOUT_SEC = 1
M.BRIDGE_PING_PROCESS_TIMEOUT_MS = 3000
M.BRIDGE_STARTUP_TIMEOUT_SEC = 10
M.BRIDGE_STARTUP_POLL_INTERVAL_SEC = 0.25
M.BRIDGE_PYTHON_DETECT_TIMEOUT_MS = 2000

M.MAX_CONTEXT_NOTES = 3000
M.MAX_HORIZONTAL_CONTEXT_NOTES = 500
M.MAX_PROGRESSION_NOTES = 800
M.MAX_CONTEXT_CC_EVENTS = 2000
M.MAX_SKETCH_NOTES = 5000
M.MAX_SKETCH_CC_EVENTS = 3000
M.HORIZONTAL_CONTEXT_RANGE_SEC = 60
M.CONTEXT_QN_ROUNDING = 100
M.DEFAULT_KEY = "unknown"
M.DEFAULT_MANUAL_KEY = "D minor"
M.DEFAULT_NOTE_DUR_Q = 0.25
M.LEGATO_NOTE_OVERLAP_Q = 1 / 32
M.SAME_PITCH_MIN_GAP_Q = 0
M.ARTICULATION_MIXED = "mixed"
M.DEFAULT_PITCH = 60
M.DEFAULT_VELOCITY = 80
M.DEFAULT_CC = 1
M.TEMPO_MARKER_MIN_BPM = 30
M.TEMPO_MARKER_MAX_BPM = 240
M.TEMPO_MARKER_MIN_GAP_Q = 0.25
M.TEMPO_MARKER_EPS_SEC = 0.0001
M.MAX_TEMPO_MARKERS = 8
M.TIME_SIG_MIN_NUM = 1
M.TIME_SIG_MAX_NUM = 32
M.TIME_SIG_VALID_DENOM = { [1] = true, [2] = true, [4] = true, [8] = true, [16] = true, [32] = true }
M.APPLY_CHUNK_SIZE = 256
M.DELETE_CHUNK_SIZE = 512

M.EXTSTATE_PROFILE_ID = "AI_PART_GENERATOR_PROFILE_ID"
M.EXTSTATE_API_PROVIDER = "AI_PART_GENERATOR_API_PROVIDER"
M.EXTSTATE_API_KEY = "AI_PART_GENERATOR_API_KEY"
M.EXTSTATE_API_BASE_URL = "AI_PART_GENERATOR_API_BASE_URL"
M.EXTSTATE_MODEL_NAME = "AI_PART_GENERATOR_MODEL_NAME"

M.EXTSTATE_ARTICULATION_NAME = "AI_PART_GENERATOR_ARTICULATION_NAME"
M.EXTSTATE_GENERATION_TYPE = "AI_PART_GENERATOR_GENERATION_TYPE"
M.EXTSTATE_GENERATION_STYLE = "AI_PART_GENERATOR_GENERATION_STYLE"
M.EXTSTATE_PROMPT = "AI_PART_GENERATOR_PROMPT"
M.EXTSTATE_USE_SELECTED_TRACKS = "AI_PART_GENERATOR_USE_SELECTED_TRACKS"
M.EXTSTATE_INSERT_TARGET = "AI_PART_GENERATOR_INSERT_TARGET"
M.EXTSTATE_KEY_MODE = "AI_PART_GENERATOR_KEY_MODE"
M.EXTSTATE_KEY = "AI_PART_GENERATOR_KEY"

M.API_PROVIDER_LOCAL = "local"
M.API_PROVIDER_OPENROUTER = "openrouter"
M.DEFAULT_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
M.DEFAULT_OPENROUTER_MODEL = "google/gemini-3-flash-preview"
M.DEFAULT_OPENROUTER_PLAN_MODEL = "google/gemini-3-pro-preview"

M.INSERT_TARGET_ACTIVE = "active"
M.INSERT_TARGET_NEW = "new"

M.EXTSTATE_FREE_MODE = "AI_PART_GENERATOR_FREE_MODE"
M.EXTSTATE_ALLOW_TEMPO_CHANGES = "AI_PART_GENERATOR_ALLOW_TEMPO_CHANGES"
M.EXTSTATE_ARRANGE_SOURCE_ITEM = "AI_PART_GENERATOR_ARRANGE_SOURCE_ITEM"

M.MIDI_MIN = 0
M.MIDI_MAX = 127
M.MIDI_VEL_MIN = 1
M.MIDI_CHAN_MIN = 1
M.MIDI_CHAN_MAX = 16
M.MIDI_CC_STATUS = 0xB0
M.MIDI_PC_STATUS = 0xC0

M.PROMPT_BUF_SIZE = 32768

M.GENERATION_TYPES = {
  "Melody",
  "Arpeggio",
  "Bass",
  "Chords",
  "Pad",
  "Counter-Melody",
  "Ostinato",
  "Rhythm",
  "Percussion",
  "Fill",
  "Atmosphere"
}

M.DEFAULT_GENERATION_TYPE = "Melody"

M.GENERATION_STYLES = {
  "Heroic",
  "Epic",
  "Cinematic",
  "Triumphant",
  "Majestic",
  "Adventurous",
  "Dramatic",
  "Intense",
  "Suspense",
  "Thriller",
  "Horror",
  "Dark",
  "Ominous",
  "Romantic",
  "Melancholic",
  "Tender",
  "Nostalgic",
  "Passionate",
  "Longing",
  "Hopeful",
  "Energetic",
  "Playful",
  "Action",
  "Aggressive",
  "Fierce",
  "Peaceful",
  "Dreamy",
  "Ethereal",
  "Mysterious",
  "Meditative",
  "Ambient",
  "Celtic",
  "Middle Eastern",
  "Asian",
  "Latin",
  "Nordic",
  "Slavic",
  "Baroque",
  "Classical",
  "Impressionist",
  "Minimalist",
  "Victorious",
  "Tragic",
  "Whimsical",
  "Serene",
  "Foreboding",
  "Magical",
  "Solemn"
}

M.DEFAULT_GENERATION_STYLE = "Heroic"

M.FALLBACK_FIELD_COUNT = 8

return M
