from __future__ import annotations

from pathlib import Path

APP_NAME = "AI Part Generator Bridge"

PROFILES_DIR = Path(__file__).resolve().parent.parent / "Profiles"

DEFAULT_PROVIDER = "lmstudio"
DEFAULT_LMSTUDIO_BASE_URL = "http://localhost:1234/v1"
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_MODEL_NAME = "local-model"
DEFAULT_OPENROUTER_MODEL = "google/gemini-3-flash-preview"
DEFAULT_ENHANCER_MODEL = "anthropic/claude-sonnet-4"
DEFAULT_TEMPERATURE = 0.7
HTTP_TIMEOUT_SEC = 300.0
LLM_RETRY_ATTEMPTS = 3
LLM_RETRY_BACKOFF_SEC = 1.0

BRIDGE_HOST = "127.0.0.1"
BRIDGE_PORT = 8000

MAX_REPAIR_ATTEMPTS = 2

MIN_CC_STEP_Q = 0.0625
MIN_NOTE_DUR_Q = 0.0625
MIN_NOTE_GAP_Q = 0.0625
TEMPO_MARKER_MIN_BPM = 30.0
TEMPO_MARKER_MAX_BPM = 240.0
TEMPO_MARKER_MIN_GAP_Q = 0.25
MAX_TEMPO_MARKERS = 8
TIME_SIG_MIN_NUM = 1
TIME_SIG_MAX_NUM = 32
TIME_SIG_VALID_DENOM = {1, 2, 4, 8, 16, 32}
KEYSWITCH_DUR_Q = 0.25
SECONDS_PER_MINUTE = 60.0
QUARTERS_PER_WHOLE = 4.0
LOG_PREVIEW_CHARS = 500
SUSTAIN_PEDAL_VALUE_OFF = 0
SUSTAIN_PEDAL_VALUE_ON = 127
SUSTAIN_PEDAL_ON_THRESHOLD = 64
SUSTAIN_PEDAL_ON_DELAY_Q = 0.1

DEFAULT_CC_INTERP = "cubic"
DEFAULT_SMOOTHING_MODE = "fixed"

MIDI_MIN = 0
MIDI_MAX = 127
MIDI_VEL_MIN = 1
MIDI_CHAN_MIN = 1
MIDI_CHAN_MAX = 16
MIDI_CHAN_ZERO_BASE_MAX = MIDI_CHAN_MAX - 1

DEFAULT_PITCH = 60
DEFAULT_VELOCITY = 80
DEFAULT_DRUM_VELOCITY = 90
DEFAULT_KEYSWITCH_VELOCITY = 100
DEFAULT_GENERATION_TYPE = "Melody"
DEFAULT_GENERATION_STYLE = "Heroic"
DEFAULT_ARTICULATION_CC = 58
ARTICULATION_PRE_ROLL_Q = 0.01
DEFAULT_PROMPT_PITCH_LOW = 48
DEFAULT_PROMPT_PITCH_HIGH = 72
PROMPT_PITCH_PREVIEW_LIMIT = 20
CUSTOM_CURVE_EXCLUSIONS = {"dynamics", "expression"}

SHORT_ARTICULATION_MAX_Q = 0.5
VERY_SHORT_ARTICULATION_MAX_Q = 0.25
ACCENT_SHORT_ARTICULATION_MAX_Q = 1.0
SHORT_ARTICULATION_FALLBACK_MAX_Q = SHORT_ARTICULATION_MAX_Q
WIND_BRASS_MAX_NOTE_DUR_Q = 4.0
WIND_BRASS_FAMILIES = {"woodwinds", "brass", "winds"}
ARTICULATION_MAX_DUR_Q = {
    "spiccato": SHORT_ARTICULATION_MAX_Q,
    "staccatissimo": VERY_SHORT_ARTICULATION_MAX_Q,
    "staccato": SHORT_ARTICULATION_MAX_Q,
    "pizzicato": SHORT_ARTICULATION_MAX_Q,
    "col_legno": SHORT_ARTICULATION_MAX_Q,
    "bartok_snap": VERY_SHORT_ARTICULATION_MAX_Q,
    "sforzando": ACCENT_SHORT_ARTICULATION_MAX_Q,
    "marcato": ACCENT_SHORT_ARTICULATION_MAX_Q,
}

LOCAL_HOSTS = {"127.0.0.1", "localhost", "::1"}
