from __future__ import annotations

try:
    from prompt_builder_common import (
        BAR_RANGE_END_OFFSET,
        BAR_RANGE_SEPARATOR,
        DEFAULT_BAR_INDEX,
        DEFAULT_BEAT_UNIT,
        DEFAULT_BEATS_PER_BAR,
        DEFAULT_GENERATION_ORDER,
        DEFAULT_TIME_SIGNATURE,
        MIN_BARS_COUNT,
        MIN_MAX_NOTES_DELTA,
        MIN_NOTES_COUNT,
        RANGE_BOUND_COUNT,
        SEMITONES_PER_OCTAVE,
        TIME_SIGNATURE_SEPARATOR,
        UNKNOWN_VALUE,
        ZERO_TIME_Q,
        extract_role_from_plan,
        import_music_notation,
        import_note_to_midi,
        is_non_empty_list,
        normalize_lower,
        normalize_text,
    )
    from prompt_builder_music import (
        bar_to_time_q,
        bars_range_to_time_q,
        estimate_note_count,
        extract_key_from_chord_map,
        get_chord_tones_from_name,
        infer_key_from_plan_chord_map,
        parse_chord_root,
        split_time_signature,
    )
    from prompt_builder_profile import (
        ARTICULATION_DURATION_HINTS,
        build_articulation_list_for_prompt,
        build_generation_progress,
        build_orchestration_hints_prompt,
        format_profile_for_prompt,
        format_profile_user_template,
        get_custom_curves_info,
        get_profile_articulation_names,
        resolve_profile_default_articulation,
        resolve_prompt_articulation,
        resolve_prompt_pitch_range,
    )
except ImportError:
    from .prompt_builder_common import (
        BAR_RANGE_END_OFFSET,
        BAR_RANGE_SEPARATOR,
        DEFAULT_BAR_INDEX,
        DEFAULT_BEAT_UNIT,
        DEFAULT_BEATS_PER_BAR,
        DEFAULT_GENERATION_ORDER,
        DEFAULT_TIME_SIGNATURE,
        MIN_BARS_COUNT,
        MIN_MAX_NOTES_DELTA,
        MIN_NOTES_COUNT,
        RANGE_BOUND_COUNT,
        SEMITONES_PER_OCTAVE,
        TIME_SIGNATURE_SEPARATOR,
        UNKNOWN_VALUE,
        ZERO_TIME_Q,
        extract_role_from_plan,
        import_music_notation,
        import_note_to_midi,
        is_non_empty_list,
        normalize_lower,
        normalize_text,
    )
    from .prompt_builder_music import (
        bar_to_time_q,
        bars_range_to_time_q,
        estimate_note_count,
        extract_key_from_chord_map,
        get_chord_tones_from_name,
        infer_key_from_plan_chord_map,
        parse_chord_root,
        split_time_signature,
    )
    from .prompt_builder_profile import (
        ARTICULATION_DURATION_HINTS,
        build_articulation_list_for_prompt,
        build_generation_progress,
        build_orchestration_hints_prompt,
        format_profile_for_prompt,
        format_profile_user_template,
        get_custom_curves_info,
        get_profile_articulation_names,
        resolve_profile_default_articulation,
        resolve_prompt_articulation,
        resolve_prompt_pitch_range,
    )
