from __future__ import annotations

MOOD_HINTS = {
    "heroic": "RISING melodic contours, strong intervals (4ths, 5ths, octaves). MAJOR tonality, bold dynamics (mf→ff). Emphasize downbeats. Confident, triumphant.",
    "epic": "GRAND sweeping lines, slow build-up. Wide intervals, unison movements. Long phrases to dramatic peaks. Dynamic swells. Majestic, powerful.",
    "triumphant": "FANFARE-like ascending motifs, bright major. Strong accents on beat 1. Celebratory, victorious. Peak dynamics at phrase ends.",
    "majestic": "SLOW dignified lines. Wide spacing, noble character. Sustained notes with gradual swells. Royal, ceremonial.",
    "adventurous": "ENERGETIC leaps, unexpected turns. Mix stepwise and wide intervals. Syncopation. Bright, forward-moving.",
    "dramatic": "Strong DYNAMIC CONTRASTS (pp↔ff). Unexpected accents. Tension intervals (m2, tritone). Emotional peaks then resolution.",
    "intense": "DRIVING ostinato, relentless motion. Crescendo passages. Dense activity. Urgent, pressing.",
    "suspense": "CHROMATIC movement, unresolved phrases. Quiet with sudden accents. Tremolo effects. Hanging, unresolved endings.",
    "thriller": "SYNCOPATED rhythms, unexpected rests. Dissonant intervals. Irregular phrase lengths. Nervous, unpredictable.",
    "horror": "CHROMATIC clusters, LOW register. Tremolo, wide leaps. Dissonant m2/tritone. Eerie, unsettling. Sudden dynamic changes.",
    "dark": "MINOR tonality, DESCENDING lines. Low-mid register. Heavy, oppressive. Slow harmonic rhythm.",
    "ominous": "SLOW creeping motion. Pedal tones with dissonant upper notes. Growing intensity. Threatening.",
    "romantic": "EXPRESSIVE rubato feel, sweeping arcs. Chromatic passing tones. Wide dynamics. Passionate, yearning.",
    "melancholic": "MINOR tonality, descending tendency. Slower feel. Suspensions, appoggiaturas. Wistful, sad.",
    "tender": "SOFT dynamics (pp-mp), close intervals (2nds, 3rds). Gentle flowing motion. Intimate, delicate.",
    "nostalgic": "SIMPLE memorable melodies. Repetitive motifs. Minor inflections in major. Bittersweet, reflective.",
    "passionate": "WIDE dynamic swings, expressive leaps. Building intensity. Emotional peaks. Heartfelt, fervent.",
    "longing": "SUSTAINED notes, yearning intervals (6ths, 7ths). Unresolved phrases. Reaching upward then falling. Aching.",
    "hopeful": "MAJOR tonality, RISING phrases. Gradual crescendo. Resolution on bright notes. Optimistic, uplifting.",
    "energetic": "FAST rhythmic activity, accented staccato. Syncopation for drive. Loud dynamics. Vigorous, lively.",
    "playful": "LIGHT staccato, melodic leaps. Major tonality. Dance-like rhythms. Cheerful, whimsical.",
    "action": "DRIVING ostinato, rapid passages. Accents on weak beats. Relentless motion. Exciting, tense.",
    "aggressive": "SHARP accents, marcato. Dissonant intervals. Strong dynamics. Forceful, attacking.",
    "fierce": "RAPID aggressive motion. Wide leaps, sforzando accents. Intense dynamics. Wild, untamed.",
    "peaceful": "SIMPLE consonant intervals (3rds, 6ths). Slow harmonic rhythm. Soft dynamics. Calm, serene.",
    "dreamy": "FLOWING arpeggiated figures, blurred phrase boundaries. High register. Soft. Floating, ethereal.",
    "ethereal": "HIGH register, sustained tones. Open intervals (4ths, 5ths). Sparse texture. Otherworldly, celestial.",
    "mysterious": "UNUSUAL intervals, ambiguous tonality. Quiet dynamics. Unexpected melodic turns. Enigmatic.",
    "meditative": "MINIMAL motion, repeated patterns. Consonant intervals. Very slow feel. Contemplative, zen.",
    "ambient": "LONG sustained notes, slow evolution. Minimal melodic activity. Atmospheric, spatial.",
    "celtic": "PENTATONIC scale, characteristic 4th/5th leaps. Ornamental grace notes. Dance-like. Folk, earthy.",
    "middle eastern": "PHRYGIAN/harmonic minor. Ornamental melismas. Augmented 2nd intervals. Exotic, mystical.",
    "asian": "PENTATONIC scale. Sparse texture. Contemplative pauses. Elegant, refined.",
    "latin": "SYNCOPATED rhythms, major tonality. Dance patterns. Warm, rhythmic.",
    "nordic": "OPEN 5ths, folk simplicity. Haunting minor melodies. Vast, cold, ancient.",
    "slavic": "MINOR tonality, characteristic intervals. Melancholic yet powerful. Folk dance elements.",
    "baroque": "SEQUENCES, ornaments (trills). Continuous motion. Contrapuntal. Elegant, formal.",
    "classical": "BALANCED 4+4 bar phrases. Clear periodic structure. Symmetric melodic shapes. Elegant.",
    "impressionist": "WHOLE-TONE and modal inflections. Blurred phrase boundaries. Coloristic, atmospheric.",
    "minimalist": "REPETITIVE patterns with subtle variations. Phase shifting. Hypnotic, evolving.",
    "victorious": "ASCENDING fanfare figures. Bright major. Strong downbeat accents. Celebrating, conquering.",
    "tragic": "DESCENDING minor lines. Slow, heavy rhythm. Lamenting intervals. Sorrowful, devastating.",
    "whimsical": "UNEXPECTED leaps, playful rhythms. Light articulation. Quirky, fantastical.",
    "serene": "CONSONANT intervals, gentle motion. Soft throughout. Tranquil, undisturbed.",
    "foreboding": "LOW register, slow chromatic motion. Building tension. Warning, threatening.",
    "magical": "SPARKLING high notes, arpeggiated figures. Whole-tone touches. Enchanting, wondrous.",
    "solemn": "SLOW hymn-like motion. Dignified intervals. Reverent, grave.",
}

DYNAMICS_HINTS = {
    "heroic": "EXPRESSION: Strong crescendo 70→110. DYNAMICS: Bold swells within phrases, accent peaks.",
    "epic": "EXPRESSION: Grand build 50→120 to peak. DYNAMICS: Sweeping phrase arcs, dramatic swells.",
    "triumphant": "EXPRESSION: High plateau 90-115. DYNAMICS: Fanfare-like accent swells on peaks.",
    "majestic": "EXPRESSION: Steady 80-95. DYNAMICS: Slow dignified swells, no sudden changes.",
    "adventurous": "EXPRESSION: Varied 70-100. DYNAMICS: Energetic note swells, sudden bursts.",
    "dramatic": "EXPRESSION: Extreme contrasts 30↔110. DYNAMICS: Intense internal swells per phrase.",
    "intense": "EXPRESSION: Relentless rise 70→120. DYNAMICS: Driving swells, no backing off.",
    "suspense": "EXPRESSION: Quiet 25-50. DYNAMICS: Sudden sfz spikes 100+, return to quiet.",
    "thriller": "EXPRESSION: Unpredictable 40-100. DYNAMICS: Nervous irregular accent swells.",
    "horror": "EXPRESSION: Eerie quiet 20-35. DYNAMICS: Terrifying sfz spikes 110+, fast decay.",
    "dark": "EXPRESSION: Heavy 70-90, descending. DYNAMICS: Oppressive, slow internal swells.",
    "ominous": "EXPRESSION: Growing threat 15→80. DYNAMICS: Creeping swells, never resolve.",
    "romantic": "EXPRESSION: Wave-like 50-100-50. DYNAMICS: Expressive phrase breathing.",
    "melancholic": "EXPRESSION: Soft 35-60, fading. DYNAMICS: Gentle decrescendos within notes.",
    "tender": "EXPRESSION: Intimate 25-50. DYNAMICS: Delicate, minimal internal movement.",
    "nostalgic": "EXPRESSION: Bittersweet 55-75. DYNAMICS: Gentle swells always returning softer.",
    "passionate": "EXPRESSION: Wide swings 50-110. DYNAMICS: Intense phrase swells, follow emotion.",
    "longing": "EXPRESSION: Yearning rise 40→90→60. DYNAMICS: Reaching swells that fade unfulfilled.",
    "hopeful": "EXPRESSION: Brightening 55→105. DYNAMICS: Uplifting phrase arcs.",
    "energetic": "EXPRESSION: High constant 90-110. DYNAMICS: Punchy accent swells on beats.",
    "playful": "EXPRESSION: Light 70-85. DYNAMICS: Bouncy, playful note swells.",
    "action": "EXPRESSION: Driving 90-100. DYNAMICS: Sfz swells 110+ on action beats.",
    "aggressive": "EXPRESSION: Forceful 100-115. DYNAMICS: Marcato attack swells 120+.",
    "fierce": "EXPRESSION: Maximum 110-127. DYNAMICS: Wild explosive sfz swells.",
    "peaceful": "EXPRESSION: Calm constant 30-50. DYNAMICS: Barely any variation, serene.",
    "dreamy": "EXPRESSION: Floating 35-60. DYNAMICS: Slow breathing swells like waves.",
    "ethereal": "EXPRESSION: Distant 15-35. DYNAMICS: Celestial whispers, subtle movement.",
    "mysterious": "EXPRESSION: Quiet 40-55. DYNAMICS: Unexpected swells and drops.",
    "meditative": "EXPRESSION: Still 30-40. DYNAMICS: Minimal movement, zen-like.",
    "ambient": "EXPRESSION: Static 30-60. DYNAMICS: Imperceptible slow changes.",
    "celtic": "EXPRESSION: Dance-like 70-85. DYNAMICS: Rhythmic accent swells.",
    "middle eastern": "EXPRESSION: Ornamental 55-80. DYNAMICS: Melodic phrase swells.",
    "asian": "EXPRESSION: Refined 40-75. DYNAMICS: Thoughtful phrase-end fades.",
    "latin": "EXPRESSION: Warm 75-95. DYNAMICS: Syncopated accent punches.",
    "nordic": "EXPRESSION: Vast 55-80. DYNAMICS: Sparse, austere swells.",
    "slavic": "EXPRESSION: Emotional 50-95. DYNAMICS: Folk-like intense phrase arcs.",
    "baroque": "EXPRESSION: Terraced jumps 45↔90. DYNAMICS: Ornamental swells within levels.",
    "classical": "EXPRESSION: Balanced 55-80. DYNAMICS: Gradual phrase crescendo/decrescendo.",
    "impressionist": "EXPRESSION: Coloristic 40-75. DYNAMICS: Blurred overlapping swells.",
    "minimalist": "EXPRESSION: Constant 60-70. DYNAMICS: Hypnotic micro-shifts.",
    "victorious": "EXPRESSION: Triumphant 95-115. DYNAMICS: Fanfare peak swells 120+.",
    "tragic": "EXPRESSION: Descending 70→25. DYNAMICS: Lamenting phrase fades.",
    "whimsical": "EXPRESSION: Quirky 70-85. DYNAMICS: Unexpected surprise swells.",
    "serene": "EXPRESSION: Undisturbed 30-50. DYNAMICS: Flat, peaceful, minimal.",
    "foreboding": "EXPRESSION: Creeping rise 15→70. DYNAMICS: Dread-building swells.",
    "magical": "EXPRESSION: Base 45, sparkles 80-90. DYNAMICS: Bright accent swells.",
    "solemn": "EXPRESSION: Reverent 55-80. DYNAMICS: Dignified steady swells.",
}
